# Generated by Django 4.1 on 2023-02-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_reviews_name_reviews_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='author',
            new_name='user',
        ),
    ]
