# Generated by Django 4.1 on 2023-05-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_author_reviews_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
